#define EACH_TEST(_)                    \
    _(arena)                            \
    _(buffer_putc)                      \
    _(buffer_printf)                    \
    _(buffer_alloc)                     \
    _(buffer_read_file)                 \
    _(read_be_bytes)                    \
    _(write_be_bytes)                   \
    _(buffer_put_be_bytes)              \
    _(compiler_examples)                \
    _(compile_int)                      \
    _(compile_string)                   \
    _(lexer_full_example)               \
    _(lexer_empty)                      \
    _(lexer_empty_string_after_keyword) \
    _(lexer_unclosed_string)            \
    _(lexer_unclosed_block_comment)     \
    _(lexer_unclosed_decimal)           \
    _(lexer_under)                      \
    _(lexer_minus_and_rarrow)           \
    _(parser_full_example)              \
    _(parser_examples)                  \
    _(snapshot_diff)                    \
    _(snapshot_diff_empty_lines)        \
    _(snapshot_diff_line_endings)       \
    _(string_pool)                      \
    _(buffer_print_c_string_literal)    \
    _(hvalue_ownership)                 \
    _(hvalue_clone)                     \
    _(hvalue_uniq)                      \
    _(hvalue_string)                    \
    _(hvalue_closure)                   \
    _(hvalue_cons)                      \
    _(hvalue_tuple)                     \
    _(hvalue_native)                    \
    _(vector)
