name: CI

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CLANG_VERSION: "21.1.8"

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      TEST_ASAN: 1
    steps:
      - uses: actions/checkout@v4
      - uses: KyleMayes/install-llvm-action@v2
        with:
          version: ${{ env.CLANG_VERSION }}
      - run: make test
        env:
          CFLAGS: -Werror
          LLVM_COVERAGE: 1
      - run: make selftest
      - uses: zgosalvez/github-actions-report-lcov@v7.0.10
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-files: coverage/*.lcov
          update-comment: true

  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: KyleMayes/install-llvm-action@v2
        with:
          version: ${{ env.CLANG_VERSION }}
      - run: make format-check
